### ISSUE TITLE
How to random crop in imgaug?

### ISSUE THREAD

**Issue by John1231983** [fabioperez/pytorch-examples#1]
In pytorch, I used
```
transforms.Resize((300,300)),
transforms.RandomCrop((224, 224)),
        
```

How should I do with imgaug to obtain the same result as above? Thanks

**Comment by fabioperez** [comment]
I guess you could use `CropAndPad` or `Crop`, but I'm not sure. I usually use the `RandomResizedCrop` from PyTorch. Maybe it's better to ask in the imgaug repository.

**Comment by John1231983** [comment]
I fixed it by using random crop in pytorch but have to convert back to PIL
